# Generated by Django 2.1.7 on 2019-04-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onetomany', '0004_auto_20190416_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=30),
        ),
    ]
